kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: ingress-manager-rb

subjects:
- kind: ServiceAccount
  namespace: default
  # 用户名称
  name: ingress-manager-sa

roleRef:
  kind: Role
  # 角色名称
  name: ingress-manager-role
  apiGroup: rbac.authorization.k8s.io
