apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.appcontroller.wangjiahao.com
spec:
  group: appcontroller.wangjiahao.com
  names:
    kind: App
    listKind: AppList
    plural: apps
    singular: app
   scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              deployment:
                properties:
                  image:
                    type: string
                  name:
                    type: string
                  replicas:
                    format: int32
                    type: integer
                required:
                - image
                - name
                - replicas
                type: object
              service:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              ingress:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
            required:
            - deployment
            - service
            - ingress
            type: object
        required:
        - spec
        type: object
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

